# -*- coding: utf-8 -*-
"""MovieRecommendationSystem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsW6FISvoKugn36PmYUsGHGt3P8nHnR5
"""

#importing libraries
import numpy as np #Library for fast numerical operations using arrays.
import pandas as pd #data manipulation
import difflib #closest match to the user input
from sklearn.feature_extraction.text import TfidfVectorizer #raw text -> numerical value
from sklearn.metrics.pairwise import cosine_similarity #to find the similarities

"""Data Collection and Pre-Processing"""

# Install kagglehub
!pip install -q kagglehub[pandas-datasets]

# Import libraries
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd

# Load the dataset
movies_data = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "harshshinde8/movies-csv",
    "movies.csv"   # file name inside the dataset
)

# Display first 5 rows
print(movies_data.head())

#number of rows and columns in the data frame
movies_data.shape

#feature selection - Choosing important columns for recommendation.
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

#replace null values for the selected_features
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

'''
Why?
TF-IDF cannot process NaN/null.
'''

#combining all the 5 selected features
combined_features = movies_data['genres']+" "+movies_data['keywords']+" "+movies_data['tagline']+" "+movies_data['cast']+" "+movies_data['director']
print(combined_features)

#convert text data to feature vectors
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)


# WTF SO COOL!
'''
TF-IDF Vectorizer (INTERNAL WORKING)
Description

Converts words into mathematical vectors.

Internal Steps
Split text into words
Count word frequency (TF)
Reduce importance of common words (IDF)
Create vectors
Example
Batman action hero
Superman action hero

action & hero become less important because both movies have them.
'''

"""Cosine Similarity

"""

#finding similarity
similarity = cosine_similarity(feature_vectors)
print(similarity)
print(similarity.shape)

'''
Cosine Similarity
Description

Measures angle between vectors to check similarity.

Method
similarity = cosine_similarity(feature_vectors)
Internal Idea
Similar movies → vectors point same direction
Value close to 1 = very similar
Value close to 0 = not similar
Formula

cos(θ)= A⋅B // ∣∣A∣∣∣∣B∣∣
	​
'''

#getting the user name from the user
movie_name = input("Enter you faviorite movie name: ")

# creating a list with all the movie names given in the dataset
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

#finidng the close match for the movie name given by the user.
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

'''
difflib
Description
Finds closest matching text.
Method
difflib.get_close_matches()
Example
User types: avatr
Returns: Avatar
'''

close_match = find_close_match[0]
print(close_match)

#find the index of the movie + title
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

#getting l ist of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)
#enumerate = looping the list at once

len(similarity_score)

#sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

#print the name of similar movies based on the index
print('Movies suggested for you: \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index == index]['title'].values[0]
  if (i <= 30):
    print(i, '.', title_from_index)
    i += 1

  '''
What Happens?
Loop through similar movies
Get movie index
Find movie title using index
Print top 30 recommendations
Important Part
.values[0]

Means:

“Give me the actual first value from the result.”
  '''

# Movie Recommendation System:

#getting the user name from the user
movie_name = input("Enter you faviorite movie name: ")

# creating a list with all the movie names given in the dataset
list_of_all_titles = movies_data['title'].tolist()
close_match = find_close_match[0]

#find the index of the movie + title
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

#sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

#print the name of similar movies based on the index
print('Movies suggested for you: \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index == index]['title'].values[0]
  if (i <= 30):
    print(i, '.', title_from_index)
    i += 1